server:
  shutdown: graceful
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: gateway
  cache:
    type: none
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        pool:
          max-life-time: 60s
          max-idle-time: 1s

management:
  endpoints:
    web:
      base-path: /_stats
      exposure:
        include: [ "health" ]
